name: resilient_erik
services:
  opds-server:
    build:
      context: .
      dockerfile: Dockerfile
    cpu_shares: 90
    command: []
    container_name: opds-server
    deploy:
      resources:
        limits:
          memory: 15766M
    environment:
      - BOOKS_DIR=/app/books
      - HOST=0.0.0.0
      - PORT=3000
    hostname: opds-server
    image: koalilla/opds-server:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/DanielPereod/opds-server-go/static/icon.png
    ports:
      - target: 3000
        published: "3423"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Media/Books
        target: /app/books
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./books:/books
      - ./calibre-config:/config
    ports:
      - "8081:8080" # Interfaz web de Calibre
    restart: unless-stopped
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/DanielPereod/opds-server-go/static/icon.png
  index: /admin
  is_uncontrolled: false
  port_map: "3423"
  scheme: http
  store_app_id: resilient_erik
  title:
    custom: OPDS Server
    en_us: opds-server
