version: '3.8'
services:
  opds-server:
    build: .
    image: opdshelf:latest
    container_name: opds-server
    ports:
      - "3222:3000"
    volumes:
      - /large/media/books:/app/books
    restart: unless-stopped
    environment:
      - PORT=3000
      - HOST=0.0.0.0
networks:
  default:
    external: true
    name: shared_net
